vim.keymap.set("n", "<leader>h", ":wincmd h<CR>", { desc = "Navigate to right pane" })
vim.keymap.set("n", "<leader>l", ":wincmd l<CR>", { desc = "Navigate to left pane" })
vim.keymap.set("n", "<leader>e", "$", { desc = "Go to end of line" })
vim.keymap.set("n", "<leader>s", "^", { desc = "Go to start of line" })
vim.keymap.set("n", "<space>c", "yy", { desc = "Copy line" })
vim.keymap.set("n", "<leader>w", ":wincmd w<CR>", { desc = "Save" })
vim.keymap.set("n", "<leader>o", "o<Esc>", { desc = "Insert new line" })
vim.keymap.set("n", "<leader>ne", ":Neotree filesystem reveal left<CR>", {})
vim.keymap.set("n", "<leader>f", "F", { desc = "Cursor to the Nth occurrence of {char} to the left" })
vim.keymap.set("n", "<leader>gf", vim.lsp.buf.format, {})
vim.keymap.set("n", "K", vim.lsp.buf.hover, {})
vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, {})
vim.keymap.set("n", "<leader>gr", vim.lsp.buf.references, {})
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, {})
